libbpf: modify makefiles to utilise the new libbpf submodule
Utilise the libbpf submodule instead of the local libbpf headers,
this repo contains the latest libbpf and also is less likely
to cause compilation errors for the user.

Signed-off-by: David Beckett <david.beckett@netronome.com>
Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>

diff --git a/xdpdump/Makefile b/xdpdump/Makefile
--- a/xdpdump/Makefile
+++ b/xdpdump/Makefile
@@ -6,57 +6,33 @@ LLC ?= llc
 CLANG ?= clang
 CC ?= gcc
 
+LIBBPF_DIR = ../libbpf/src/
+
 XDP_C = ${TARGET:=_kern.c}
 XDP_OBJ = ${XDP_C:.c=.o}
 USER_C = ${TARGET:=_user.c}
 USER_OBJ = ${USER_C:.c=.o}
+OBJECT_LIBBPF = $(LIBBPF_DIR)/libbpf.a
 
-# LIBS REQUIRED FOR USER PROG
-OBJECT_NLATTR = ../kernel/tools/lib/bpf/nlattr.o
-OBJECT_BTF = ../kernel/tools/lib/bpf/btf.o
-OBJECT_BPF_SYSCALLS = ../kernel/tools/lib/bpf/bpf.o
-OBJECT_LIBBPF = ../kernel/tools/lib/bpf/libbpf.o
-OBJECTS = $(OBJECT_NLATTR) $(OBJECT_BTF) $(OBJECT_BPF_SYSCALLS) $(OBJECT_LIBBPF)
-
-KERNEL ?= /lib/modules/$(shell uname -r)/build/
-
-CFLAGS ?= -I../kernel/tools
+CFLAGS ?= -I$(LIBBPF_DIR)/root/usr/include/
+CFLAGS += -I../kernel/tools
 CFLAGS += -I../kernel/tools/include
 CFLAGS += -I../kernel/tools/lib
 CFLAGS += -I../kernel/tools/perf
+LDFLAGS ?= -L$(LIBBPF_DIR)
 
-CFLAGS_LIBBPF ?= -I$(KERNEL)/tools/include
-CFLAGS_LIBBPF += -I$(KERNEL)/tools/perf
-CFLAGS_LIBBPF += -I$(KERNEL)/usr/include
-CFLAGS_LIBBPF += -I$(KERNEL)/arch/x86/include
-CFLAGS_LIBBPF += -I../kernel/tools/perf
+LIBS = -lbpf -lelf
 
-LDFLAGS = -lelf
-
-all: llvm-check kernel-source-devel-headers $(TARGET) $(XDP_OBJ)
+all: llvm-check $(TARGET) $(XDP_OBJ)
 
 .PHONY: clean $(CLANG) $(LLC)
 
 clean:
-	rm -f $(OBJECTS)
+	cd $(LIBBPF_DIR) && $(MAKE) clean;
 	rm -f $(TARGET)
 	rm -f $(XDP_OBJ)
 	rm -f $(USER_OBJ)
 	rm -f *.ll
-
-kernel-source:
-	@if [ ! -d $(KERNEL)/ ]; then \
-		echo "(No source code located at $(KERNEL)) " ;\
-		exit 1; \
-	else true; fi
-
-kernel-source-devel-headers: kernel-source
-	@if [ ! -d $(KERNEL)/usr/include/ ]; then \
-		echo "Error: Need kernel headers"; \
-		echo "May need to run make headers_install within"; \
-		echo "$(KERNEL)"; \
-		exit 1; \
-	else true; fi
 
 llvm-check: $(CLANG) $(LLC)
 	@for TOOL in $^ ; do \
@@ -66,12 +42,18 @@ llvm-check: $(CLANG) $(LLC)
 		else true; fi; \
 	done
 
-# LIBBPF OBJECTS
-$(OBJECTS): %.o: %.c
-	$(CC) $(CFLAGS_LIBBPF) -o $@ -c $<
+$(OBJECT_LIBBPF):
+	@if [ ! -d $(LIBBPF_DIR) ]; then \
+		echo "Error: Need libbpf submodule"; \
+		echo "May need to run git submodule update --init"; \
+		exit 1; \
+	else \
+		cd $(LIBBPF_DIR) && $(MAKE) all; \
+		mkdir -p root; DESTDIR=root $(MAKE) install_headers; \
+	fi
 
-$(TARGET): %: %_user.c $(OBJECTS) Makefile
-	$(CC) $(CFLAGS) $(OBJECTS) $(LDFLAGS) -o $@ $<
+$(TARGET): %: %_user.c $(OBJECT_LIBBPF) Makefile
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LIBS)
 
 $(XDP_OBJ): %.o: %.c
 	$(CLANG) -S \
